### ISSUE TITLE
Is it possible to add comick.app?

### ISSUE THREAD

**Issue by anotherduckling** [MooshiMochi/ManhwaUpdatesBot#1]

**Comment by anotherduckling** [comment]
Btw the bot looks very helpful. An embed system will make it cooler.

**Comment by MooshiMochi** [comment]
Hey!

I'll look around and contact the owner first to see if they have an API I could use. If they don't I'll try scraping and praying that the Cloudflare security level isn't too high for the website.

By the way, can you explain in more detail what you meant by embed system?

**Comment by MooshiMochi** [comment]
I sent an email to the owner/team at comick.app and am now waiting for a response.
Additionally, I looked around the website and it seems that scraping the website will be possible, but I cannot make any guarantees.

Thank you for leaving this suggestion!
