### ISSUE TITLE
Manage_roles

### ISSUE THREAD

**Issue by agido1234** [MooshiMochi/ManhwaUpdatesBot#10]
I'm unable to track manga/manwha because it requires permissions to manage roles. I gave the bot permission and it always permissions but suddenly It's unable to track even with permission. 
![e70a7314eeb68f5f9bc5d0206e605a9e](https://github.com/MooshiMochi/ManhwaUpdatesBot/assets/128093809/fef393dd-21ba-4f83-a2b5-c758a0180c5c)

**Comment by MooshiMochi** [comment]
fixed
