### ISSUE TITLE
mangasiamese.com

### ISSUE THREAD

**Issue by MaiSan9999** [MooshiMochi/ManhwaUpdatesBot#4]
https://mangasiamese.com/ support

**Comment by MooshiMochi** [comment]
👍 Added!
https://github.com/MooshiMochi/ManhwaUpdatesBot/blob/master/README.md?plain=1#L89
https://github.com/MooshiMochi/ManhwaUpdatesBot/blob/master/src/core/scanlators/lookup_map.json#L1109-L1176
