### ISSUE TITLE
Another Website Request

### ISSUE THREAD

**Issue by 101Suni101** [MooshiMochi/ManhwaUpdatesBot#9]
https://zinmanga.io/
https://cypherscans.xyz/
https://platinumscans.com/
https://globalbloging.com/
https://theguildscans.com/
https://edomae.co/
https://www.scyllascans.org/
https://gourmetsupremacy.com/
https://disasterscans.com/
https://tritinia.org/
https://alandal.com/
https://homeheroscans.com/
https://dragontea.ink/

I think, That's enough for now

**Comment by MooshiMochi** [comment]
Do you actually use all of the requested websites?

If not, can you tell me which websites you use so I can prioritise those.

**Comment by 101Suni101** [comment]
> Do you actually use all of the requested websites?
> 
> If not, can you tell me which websites you use so I can prioritise those.

Dragon tea, cypher scans, platinum scans,

**Comment by MooshiMochi** [comment]
> > Do you actually use all of the requested websites?
> > If not, can you tell me which websites you use so I can prioritise those.
> 
> Dragon tea, cypher scans, platinum scans,

ok, I'll put a priority on those.
While you're at it, you should join the [support server](https://github.com/MooshiMochi/ManhwaUpdatesBot?tab=readme-ov-file#support) :)

**Comment by MooshiMochi** [comment]
https://zinmanga.io/ - Will add it in a future update
https://cypherscans.xyz/ - Cannot access the website atm. Will try again another time
https://platinumscans.com/ - Uses old ajax version. Website will update it soon (according to owner) so I will wait until then.
https://globalbloging.com/ - Too few series being scanlated.
https://theguildscans.com/ - Too few series being scanlated.
https://edomae.co/ - Cannot access the website atm. Will try again another time
https://www.scyllascans.org/ - Will add in a future update
https://gourmetsupremacy.com/ - Will add in a future update
https://disasterscans.com/ - Too few series being scanlated.
https://tritinia.org/ - Already supported :)
https://alandal.com/ - Has a huge amount of paid chapters. This is a horrible website IMO and would rather not add it to the bot.
https://homeheroscans.com/ - Too few series being scanlated.
https://dragontea.ink/ - Can't access website. It has an insane security level for cloudflare (idk why). I'm also banned from the discord for some reaosn.

**Comment by MooshiMochi** [comment]
Re-opening to track website additions for the new crawler backend system
